{{- if .Values.web.enabled -}}
{{- $extraEnv := list
  (dict "name" "FLAVOR" "value" "octane")
  (dict "name" "DB_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict
    "name" (include "lan-common.dbPasswordSecretName" .)
    "key"  (include "lan-common.dbPasswordSecretKey" .)
  )))
  (dict "name" "REDIS_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict
    "name" .Values.cache.existing.passwordSecret.name
    "key"  .Values.cache.existing.passwordSecret.key
  )))
-}}
{{- $envFromExtras := list -}}
{{- if .Values.mail.credentialsSecret.name -}}
{{- $envFromExtras = append $envFromExtras (dict "secretRef" (dict "name" .Values.mail.credentialsSecret.name "optional" true)) -}}
{{- end -}}
{{- $extraVolumes := list
  (dict "name" "public-cache"
        "emptyDir" (dict "sizeLimit" .Values.writablePublic.size))
-}}
{{- $extraVolumeMounts := list
  (dict "name" "public-cache"
        "mountPath" "/var/www/html/public/cache"
        "readOnly" false)
-}}
{{- include "lan-common.deployment" (dict
    "context" .
    "component" "web"
    "values" .Values.web
    "extraEnv" $extraEnv
    "envFromExtras" $envFromExtras
    "extraVolumes" $extraVolumes
    "extraVolumeMounts" $extraVolumeMounts
) }}
{{- end -}}
