{{- $extraEnv := list
  (dict "name" "FLAVOR" "value" "octane")
  (dict "name" "DB_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict
    "name" (include "lan-common.dbPasswordSecretName" .)
    "key"  (include "lan-common.dbPasswordSecretKey" .)
  )))
-}}
{{- include "lan-common.jobMigrate" (dict "context" . "extraEnv" $extraEnv) }}
